# Generated by Django 5.1.4 on 2025-02-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_vote_delete_yourmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
